import "./globals.css";
import ApolloProviderWrapper from '../components/ApolloProviderWrapper';
import Navbar from '../components/NavBar';





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
      <html lang="en">
      <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
      </head>
      <ApolloProviderWrapper>
          <body>
          <div style={{marginBottom:'100px'}}>
              <Navbar/>
          </div>
          {children}
          </body>
      </ApolloProviderWrapper>
      </html>
  );
}
